Add following validations based on azure storage account settings
Azure-Samples/azure-files-samples pull request #103
Opened 2022-05-10 07:38 UTC by bharathsm-ms

1. Validate SMB versions
2. Validate autheniticate mechanism
3. Validate channel encryption settings
4. Notify user about type of encryption configured for Kerbros ticket
5. In case of SMB2.1, Check secure transfer option is enabled and notify user
6. Minor bug fixes and logs

2022-06-07 14:15 UTC, sprasad-microsoft requested changes

2022-06-08 08:35 UTC, bharathsm-ms commented on AzFileDiagnostics/Linux/AzFileDiagnostics.sh
> +					print_log "Secure transfer is enabled on server, Please disable to from azure portal to mount SMB2 shares" "error"
Done

2022-06-08 08:36 UTC, bharathsm-ms commented on AzFileDiagnostics/Linux/AzFileDiagnostics.sh
> +			print_log "AES-256-GCM is supported by server for 3.1.1, but you should install cifs module on client with module parameter 'require_gcm_256' to use AES-256-GCM" "warning"
Changed accordingly and added a command to enable gcm_256

2022-06-08 08:36 UTC, bharathsm-ms commented on AzFileDiagnostics/Linux/AzFileDiagnostics.sh
> +			print_log "Unknown Encryption mechanism" "error"
Done

2022-06-08 08:37 UTC, bharathsm-ms commented on AzFileDiagnostics/Linux/AzFileDiagnostics.sh
> +			az account show
Done. The details gets printed when user does "az login". If we do "az account show" again then there will be duplicates.

2022-06-08 08:37 UTC, bharathsm-ms commented on AzFileDiagnostics/Linux/AzFileDiagnostics.sh
> +print_log "Do you want to map drive by script?" "info"
Done

2022-06-08 08:37 UTC, bharathsm-ms commented on AzFileDiagnostics/Linux/AzFileDiagnostics.sh
> +command="mount -t cifs "$UNCPATH"  "$mountpoint" -o vers="$smb_ver",username="$username",password=$password,dir_mode=0777,file_mode=0777,sec="$sec_name""
Done

2022-06-08 13:03 UTC, sprasad-microsoft approved these changes

2022-06-08 13:03 UTC, merged