Refactor
Azure-Samples/azure-files-samples pull request #147
Opened 2023-06-21 12:03 UTC by aman-1004

2023-06-21 12:08 UTC, aman-1004 commented
@microsoft-github-policy-service agree company="Microsoft"

2023-06-21 12:36 UTC, ksubmsft requested changes
SmbDiagnostics/trace-cifsbpf: 104/105: please replace the magic signal numbers in `knownErrors` by symbolic names. We know that the "-2" here is `ENOENT`, for instance.

2023-06-28 07:18 UTC, bharathsm-ms commented on NfsDiagnostics/nfsclientlogs.sh
> +  if [[ "$*" =~ "v3b" ]]
.

2023-06-29 02:59 UTC, ksubmsft approved these changes

2023-06-29 03:00 UTC, merged